import streamlit as st
st.title("🎈 Students Social Media Addiction Analysis and Prediction using Machine Learning")
st.write("The Student Social Media & Relationships dataset contains anonymized records of students’ social‐media behaviors and related life outcomes. It spans multiple countries and academic levels, focusing on key dimensions such as usage intensity, platform preferences, and relationship dynamics. Each row represents one student’s survey response, offering a cross‐sectional snapshot suitable for statistical analysis and machine‐learning applications.")
st.title("About DataSet")
st.markdown("**Student_ID** A unique integer identifier assigned to each survey respondent to enable de-duplication and track individual records without revealing personal information.")
st.markdown("**Age** The student’s age in completed years at the time of the survey, used to segment analysis by age group and control for developmental differences.")
st.markdown("**Gender** The student’s self-reported gender, recorded as “Male” or “Female” to allow for demographic breakdowns in usage and outcome measures.")
st.markdown("**Academic_Level** The highest level of education the respondent is currently enrolled in, with categories: “High School,” “Undergraduate,” or “Graduate,” facilitating stratified analyses by academic stage.")
st.markdown("**Avg_Daily_Usage_Hours** The average number of hours per day the student spends on social media platforms, calculated from self-reported weekday and weekend usage estimates.")
st.markdown("**Most_Used_Platform** The social media platform on which the student spends the most time (e.g., Instagram, Facebook, TikTok), used to examine platform-specific effects.")
st.markdown("**Affects_Academic_Performance** A binary indicator (“Yes”/“No”) reflecting whether the student perceives their social media use as having a negative impact on their academic performance.")
st.title("In this project we Implemented Using RandomForestClassifier Model:")
st.markdown("**How Random Forest Works**")
st.write("Random Forest is an ensemble machine learning method that builds multiple decision trees and combines their outputs. Here's how it works:")
st.markdown("**Multiple Decision Trees:** It trains several decision trees on different subsets of the data and features (using bootstrapping and random feature selection).")
st.markdown("**Voting Mechanism:** Each tree predicts an output, and the final prediction is the majority vote (in classification tasks like yours).")
st.markdown("**Reduces Overfitting:** Unlike a single decision tree, a forest of trees reduces the risk of overfitting, especially with noisy or complex data")
st.title("How Random Forest is Suitable for This Use Case")
st.markdown("**Handles Categorical and Numerical Features:** Your dataset includes encoded categorical variables (like Gender, Academic_Level, Platform) and numeric ones. Random Forest handles mixed data types well.")
st.markdown("**Works Well on Small to Medium Datasets:** The student social media dataset is relatively small and structured, ideal for Random Forest.")
st.markdown("**Robust to Outliers and Missing Data:** Even if your data has some noise or irregular entries, Random Forest maintains good performance.")
st.title("After Implemented this model we got Accuracy_score as 98.45%")
